### ISSUE TITLE
Cant get this to work right 

### ISSUE THREAD

**Issue by mgherghi** [nasa/isle#12]
So I have my log file for apache below, I've been trying to fix this problem for quite some time but have honestly given up. I can't figure out what it is with the connection. I can go to the webpage for my instance but all it says is "oops I'm sorry. Something went wrong. Feel free to submit a bug report."

Can anyone help ? 

**[Sat Feb 29 01:22:51.172310 2020]** [php7:notice] [pid 845] [client 192.168.171.245:62460] Uncaught PHP exception (Code 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /var/www/webroot/isle/includes/classes/DataProviders/ISLE.php on line 28\nPHP Stack trace:\n#0 /var/www/webroot/isle/includes/classes/DataProviders/ISLE.php(28): PDO->__construct('mysql:host:127....', 'root', 'root')\n#1 /var/www/webroot/isle/includes/classes/Service.php(18): ISLE\\DataProviders\\ISLE->__construct()\n#2 /var/www/webroot/isle/includes/auth.php(12): ISLE\\Service->__construct()\n#3 /var/www/webroot/isle/includes/config.php(2): require_once('/var/www/webroo...')\n#4 /var/www/webroot/isle/assets.php(3): require_once('/var/www/webroo...')\n#5 {main} *Generated by error.php
root@DietPi:~#

**Comment by PeteDiMarco** [comment]
I don't think ISLE is being actively maintained any more.  Back when I was experimenting with it, I had to do quite a bit of hacking to get authentication to work.

**Comment by mgherghi** [comment]
ah ok, thank you for the feedback. Its such a perfect match for what I needed. Can you recommend anything else ?

**Comment by PeteDiMarco** [comment]
I haven't looked at lab equipment management systems since June 2018.
If you have Jira, there's an add-on called Insight that should do the job.

**Comment by bruffridge** [comment]
Is this error occurring when running ISLE using the included Vagrant box?

**Comment by afabozzi** [comment]
Here is everything I did from start to finish. https://www.fabozzi.net/how-to-setup-the-isle-inventory-system/ 
I also could not get authentication figured out so I ignored using it since this is for internal use anyway. 
Would be interested to know what hacking is needed to get it going though.  This really is the perfect solution for what we use it for in house.
